export { default as AdminPage } from './admin/page'
export { default as HomePage } from './home/page'
export { default as LoginPage } from './login/page'
export { default as RegisterPage } from './register/page'
export { default as UserPage } from './user/page'
