export { default as Clients } from './clients/Clients'
export { default as Documents } from './documents/Documents'
export { default as Ficha } from './ficha/Ficha'
export { default as FichaForm } from './ficha/FichaForm'
export { default as Navbar } from './navbar/Navbar'
